# Generated by Django 4.2.15 on 2024-09-02 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=62, null=True)),
                ('lastname', models.CharField(max_length=62)),
                ('blogs', models.JSONField()),
                ('blogs_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 23, 0, 52, 171519))),
            ],
        ),
    ]
