# Generated by Django 4.2.15 on 2024-09-07 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userstable_options_alter_userstable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstable',
            name='blogs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userstable',
            name='blogs_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstable',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 23, 36, 49, 326681)),
        ),
    ]
