# Generated by Django 4.2.15 on 2024-09-07 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userstable_blogs_alter_userstable_blogs_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstable',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 23, 54, 14, 143239)),
        ),
        migrations.AlterField(
            model_name='userstable',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
