# Generated by Django 4.2.15 on 2024-09-08 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userstable_created_at_alter_userstable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstable',
            name='blogs',
        ),
        migrations.RemoveField(
            model_name='userstable',
            name='blogs_count',
        ),
        migrations.AlterField(
            model_name='userstable',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 1, 11, 855403)),
        ),
    ]
