# Generated by Django 3.1.4 on 2024-09-08 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userstable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstable',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 19, 37, 947516)),
        ),
    ]
