# Generated by Django 4.2.15 on 2024-09-08 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240908_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstable',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 20, 32, 594432)),
        ),
    ]
