# Generated by Django 4.2.15 on 2024-09-08 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogposts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 21, 57, 670922)),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 21, 57, 670922)),
        ),
    ]
