# Generated by Django 4.2.15 on 2024-09-08 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogposts_edited_at_blogposts_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 24, 17, 50850)),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 21, 24, 17, 50850)),
        ),
    ]
